# This is a basic workflow to help you get started with Actions
name: PanditBOT 

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the main branch
  # push:
  #   branches: [ main ]
  schedule:
    # every 2 hours from 6am IST to 6pm IST  
    - cron:  '0 0 1 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 #install the python needed
    - name: Installing dependencies
      run: |
          python -m pip install --upgrade pip
          pip install bs4    
    - name: Create new JSON # run the main.py to get the latest data
      run: python main.py
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

